### ISSUE TITLE
nk3: improve firmware update process

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#146]
Improve firmware update process for Nitrokey 3:
- [x] Improve process speed on Windows
- [x] Adapt the process for macOS so that the user does not get an error message (#145, #148)
- [x] Add --experimental switch on Windows (#144)
- [x] Add progress bar (#142, blocked by spsdk)
- [x] Add automatic image download (#138, #151)
- [x] Improve error reporting (as discussed in https://github.com/NXPmicro/spsdk/issues/23)
- [x] Fix device path type on Windows (#147)
- [x] Ignore bootloader reset failure on Windows (#147)

Connected: #143 #144 #145 #142 #138 #137

**Comment by szszszsz** [comment]
As stated in https://github.com/Nitrokey/pynitrokey/pull/176#issuecomment-1041867447, I run firmware update process on a Windows 10 PC, and it went quite fast, under 10 seconds. In that case I see this ticket as being completed, hence closing as Done.
